return {
---Level 0/1
		{		            
		            {'Dog',{{2,2}},{{'o','ou','uo','aw'}}},
		            {'Boat',{{2,3}},{{'oa','o','ou','oo'}}},
		            {'House',{{2,3}},{{'ou','o','uo','oo'}}},
		            {'Apple',{{2,3}},{{'pp','p','pe','pl'}}},
		            {'Pen',{{2,2}},{{'e','en','ee','ea'}}},
		            {'Clock',{{3,4}},{{'oc','o','oo','ok'}}},
		            {'Play',{{3,3}},{{'a','la','e','ei'}}},
					{'Mother',{{3,4}},{{'th','t','dh','ht'}}},
					{'Father',{{3,4}},{{'th','t','dh','ht'}}},
					{'Sister',{{3,4}},{{'st','sst','sth','sh'}}},
					{'Food',{{2,3}},{{'oo','ou','uo','o'}}},
					{'Brother',{{4,5}},{{'th','h','t','ht'}}}
            },
---Level 2            
			{
		           	{'Coffee',{{3,4}},{{'ff','of','f','uf'}}},
		           	{'Queen',{{2,3}},{{'ue','u','oe','o'}}},
		           	{'Water',{{2,2}},{{'a','o','oo','ae'}}},
		           	{'Mobile',{{2,2}},{{'o','ou','oo','a'}}},
		            {'Neighbor',{{3,5}},{{'igh','yh','ih','ygh'}}},
		            {'Shoe',{{2,3}},{{'ho','oo','hu','o'}}},
		            {'Cowboy',{{2,3}},{{'ow','o','oo','oow'}}},
		            {'Glasses',{{4,5}},{{'ss','s','es','se'}}},
		            {'Chair',{{3,4}},{{'ai','a','ei','e'}}},
		            {'Button',{{2,3}},{{'ut','u','ot','o'}}},
		            {'Library',{{4,5}},{{'ra','r','ar','a'}}}
			},
---Level 3			
			{
		            {'Guitar',{{2,3}},{{'ui','uu','u','i'}}},
		            {'Question',{{2,3}},{{'ue','oe','u','e'}}},
		            {'Difficult',{{7,7}},{{'u','o','uu','oo'}}},
		            {'Difficult',{{3,4}},{{'ff','f','fu','if'}}},
		            {'Acceptable',{{7,7}},{{'a','ae','e','ea'}}},
		            {'Acceptable',{{2,3}},{{'cc','c','ce','e'}}},
		            {'Committed',{{3,4}},{{'mm','om','m','o'}}},
		            {'Intelligence',{{9,9}},{{'e','ee','a','ie'}}},
		            {'Intelligence',{{5,6}},{{'ll','l','el','li'}}},
		            {'Yesterday',{{6,7}},{{'rd','d','rp','ld'}}},
					{'Requirement',{{3,4}},{{'qu','q','eq','qa'}}},
					{'Millennium',{{3,4}},{{'ll','l','il','le'}}},
					{'Miniature',{{7,7}},{{'u','e','i','ue'}}}
			},
--- Level 4			
			{
		           	{'Artichoke',{{3,4}},{{'ti','tie','te','to'}}},
		            {'Scrummaster',{{2,3}},{{'cr','ckr','kr','crr'}}},
		            {'Scrummaster',{{5,6}},{{'mm','m','me','mm'}}},
		            {'Acquire',{{2,3}},{{'cq','cc','q','k'}}},
		            {'Rhythm',{{2,3}},{{'hy','y','yi','hu'}}},
		            {'Vacuum',{{3,4}},{{'cu','k','c','cc'}}},
		            {'Jewelry',{{2,3}},{{'ew','aw','ev','av'}}},
		            {'Judgment',{{3,4}},{{'dg','d','g','ug'}}},
		            {'Leisure',{{2,3}},{{'ei','ie','e','i'}}},
		            {'Weird',{{2,3}},{{'ei','ie','e','i'}}},
		            {'Sergeant',{{5,6}},{{'ea','ee','a','aa'}}},
		            {'Schedule',{{2,3}},{{'ch','c','h','he'}}}
		           
			},
--- Level 5			
			{
		          	{'Questionnaire',{{2,3}},{{'ue','oe','u','e'}}},
		            {'Playwright',{{5,6}},{{'wr','r','whr','ir'}}},
		            {'Hierarchy',{{2,3}},{{'ie','i','e','ee'}}},
		            {'Accommodate',{{2,3}},{{'cc','c','cq','ck'}}},
		            {'Conscientious',{{9,10}},{{'ti','sc','sh','ta'}}},
		            {'Conscientious',{{4,5}},{{'sc','ti','sh','c'}}},
		            {'Pronunciation',{{5,6}},{{'un','an','en','in'}}},
		            {'Misspelled',{{7,8}},{{'ll','l','el','le'}}},
		            {'Misspelled',{{3,4}},{{'ss','s','es','se'}}},
		            {'Presbyterian',{{4,6}},{{'sby','sbe','sbi','cby'}}},
		            {'Occurrence',{{3,3}},{{'c','u','cu','k'}}},
		            {'Noticeable',{{2,2}},{{'o','oo','u','ou'}}},
		            {'Threshold',{{4,4}},{{'e','ae','a','ee'}}}
			},
--- Level 6			
			{
		            {'Accommodate',{{2,3}},{{'cc','c','cq','ck'}}},
		            {'Accommodate',{{5,6}},{{'mm','m','em','am'}}},
		            {'Conscientious',{{9,10}},{{'ti','sc','sh','ta'}}},
		            {'Conscientious',{{4,5}},{{'sc','ti','sh','c'}}},
		            {'Pronunciation',{{10,11}},{{'ti','ch','sh','te'}}},
		            {'Pronunciation',{{5,6}},{{'un','an','en','in'}}},
		            {'Presbyterian',{{4,6}},{{'sby','sbe','sbi','cby'}}}
			}
  }