profiles = { ['player1'] = {name = 'Per', isActive = true,
			 mathGame = {userLevel = 1, additionPoints = 0, subtractionPoints = 0, multiplicationPoints = 0, divisionPoints = 0},
			 geographyGame = 1, spellingGame = 1, memoryGame = 1},
			 ['player2'] = {name = 'Frida', isActive = true,
			 mathGame = {userLevel = 1, additionPoints = 0, subtractionPoints = 0, multiplicationPoints = 0, divisionPoints = 0},
			 geographyGame = 1, spellingGame = 1, memoryGame = 1},
			 ['player3'] = {name = '', isActive = false,
			 mathGame = {userLevel = 1, additionPoints = 0, subtractionPoints = 0, multiplicationPoints = 0, divisionPoints = 0},
			 geographyGame = 1, spellingGame = 1, memoryGame = 1},
			 ['player4'] = {name = '', isActive = false,
			 mathGame = {userLevel = 1, additionPoints = 0, subtractionPoints = 0, multiplicationPoints = 0, divisionPoints = 0},
			 geographyGame = 1, spellingGame = 1, memoryGame = 1} }